include(${CMAKE_CURRENT_LIST_FILE}/../detect_compiler_and_platform.cmake)
include(${CMAKE_CURRENT_LIST_FILE}/../detect_operating_system.cmake)
include(${CMAKE_CURRENT_LIST_FILE}/../set_default_project_properties.cmake)
include(${CMAKE_CURRENT_LIST_FILE}/../set_default_module_properties.cmake)
include(${CMAKE_CURRENT_LIST_FILE}/../templates.cmake)
